aggregator/aggregator/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^news/', include(('news.urls', 'news'), namespace='news'))
]

aggregator/news/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.articles_list, name='articles_list'),
    url(r'^feeds/new', views.new_feed, name='feed_new'),
    url(r'^feeds/', views.feeds_list, name='feeds_list')

]

aggregator/news/models.py
import uuid
from django.db import models

# Create your models here.

# Create the model for feeds


class Feed(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=200)
    url = models.URLField()
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.title


# create the model for Article
class Article(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    feed = models.ForeignKey('news.Feed', on_delete=models.PROTECT, null=True, blank=True)
    title = models.CharField(max_length=200)
    url = models.URLField()
    description = models.TextField()
    publication_date = models.DateTimeField()

    class Meta:
        """Extra model properties."""

        ordering = ['-publication_date']

    def __str__(self):
        return self.title

aggregator/news/forms.py
from django import forms

from .models import Feed

class FeedForm(forms.ModelForm):
    class Meta:
        model = Feed
        fields = ('url',)

aggregator/news/views.py
from django.shortcuts import render
from .models import Article, Feed
from .forms import FeedForm
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone

import feedparser
import datetime

# Create your views here.


def articles_list(request):
    """Get the list of the article"""
    articles = Article.objects.all()

    rows = [articles[x:x+1] for x in range(0, len(articles), 1)]

    return render(request, 'news/articles_list.html', {'rows': rows})


def feeds_list(request):
    feeds = Feed.objects.all()
    return render(request, 'news/feeds_list.html', {'feeds': feeds})


def get_entries(url):
    feed_data = feedparser.parse(url)

    if feed_data.get("entries"):
        return feed_data.get("entries")
    return []


def get_title(url):
    feed_data = feedparser.parse(url)

    return feed_data.get("title")


def create_new_entry(feed, url):
    entries = get_entries(url)
    for entry in entries:
        date_string = timezone.now()  # init the time to now in case published_parse=False
        if entry.get('published_parse'):
            d = datetime.datetime(*(entry.published_parsed[0:6]))
            date_string = d.strftime('%Y-%m-%d %H:%M:%S')

        Article.objects.create(title=entry.get('title'),
                               url=entry.get('link'),
                               description=entry.get('description'),
                               publication_date=date_string,
                               feed=feed)
    return True


def new_feed(request):
    if request.method == "POST":
        form = FeedForm(request.POST)
        if form.is_valid():
            # get the url from the form
            feed = form.save(commit=False)

            # check if there is an existing feed with this url
            existing_feed = Feed.objects.filter(url=feed.url)
            if len(existing_feed) > 0:
                existing_feed_entries = Article.objects.filter(feed=existing_feed[0])
                if len(existing_feed_entries) == 0:
                    create_new_entry(existing_feed[0], existing_feed[0].url)
                return HttpResponseRedirect(reverse('news:feeds_list'))

            if len(existing_feed) == 0:

                # return to the form if there is an error
                get_tit = get_title(feed.url)
                if not get_tit:
                    form = FeedForm()
                    return render(request, 'news/new_feed.html', {'form': form})

                feed.title = get_tit
                feed.save()
                create_new_entry(feed, feed.url)

            return HttpResponseRedirect(reverse('news:feeds_list'))
    else:
        form = FeedForm()
    return render(request, 'news/new_feed.html', {'form': form})

aggregator/news/templates/news/articles_list.html
{% extends 'news/base.html' %}

{% block content %}

<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
  <div class="container">
    <h1>Simple News Aggregator</h1>
    <p>Have a look around to see some of the latest and greatest news articles from your favorite feeds.</p>
  </div>
</div>

<div class="container">
  {% for row in rows %}
  <div class="col-md-6">
    {% for entry in row %}
    <h2>{{entry.title}}</h2>
    <p>{{entry.description | safe}}</p>
    <p><a href="{{entry.url}}" target="_blank" class="btn btn-primary">View Details</a></p>
    {% endfor %}
  </div>
  {% endfor %}

  <footer>
    <p>&copy; 2019 Simple News Aggregator</p>
  </footer>
</div> <!-- /container -->

{% endblock %}

aggregator/news/templates/news/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Simple News Aggregator</title>

    <!-- Bootstrap core CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Simple News Aggregator</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'news:articles_list' %}">Home</a></li>
            <li><a href="{% url 'news:feeds_list' %}">Feeds</a></li>
          </ul>
        </div>
      </div>
    </nav>

    {% block content %}
    {% endblock %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  </body>
</html>

aggregator/news/templates/news/feeds_list.html
{% extends 'news/base.html' %}

{% block content %}

<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
  <div class="container">
    <h1>News Feeds</h1>
  </div>
</div>

<div class="container">
  <a href="{% url 'news:feed_new' %}" class="btn btn-primary">New Feed</a>
  <hr>
  <ul>
    {% for feed in feeds %}
      <li><a href="{{feed.url}}">{{feed.title}}</a></li>
    {% endfor %}
  </ul>

  <footer>
    <p>&copy; 2019 Simple News Aggregator</p>
  </footer>
</div> <!-- /container -->

{% endblock %}

aggregator/news/templates/news/new_feed.html
{% extends 'news/base.html' %}

{% block content %}

<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
  <div class="container">
    <h1>New Feed</h1>
  </div>
</div>

<div class="container">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <hr>
    <button type="submit" class="btn btn-primary">Save</button>
  </form>

  <footer>
    <p>&copy; 2019 Django News Aggregator</p>
  </footer>
</div> <!-- /container -->

{% endblock %}